
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_LIST_SUCESS = 'GET_PRODUCT_LIST_SUCESS';
export const GET_PRODUCT_LIST_FALIURE = 'GET_PRODUCT_LIST_FALIURE';


export const SET_CART_ITEM = 'SET_CART_ITEM';
export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS';
export const SET_CARD_DETAILS = 'SET_CARD_DETAILS';









